platform:
  name: lubancat5
  camera_device: /dev/video1
  ros_domain_id: 20
  servo_pwm:
    physical_pin: 32
    gpio_name: GPIO4_B6
    gpio_number: 142
    controller: pwm13
    pinmux: m1
    pwmchip: 3
    channel: 0
    period_ns: 20000000
